apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dkerov-dkerov-poi-map-app-dev
  annotations:
    argocd/app-name: dkerov-dkerov-poi-map-app-dev
    backstage.io/kubernetes-id: dkerov-dkerov-poi-map-app-dev
    backstage.io/kubernetes-namespace: dkerov
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=dkerov-dkerov-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/dkerov-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/dkerov/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/dkerov/deployments/dkerov-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/dkerov-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://dkerov-poi-map-app-dkerov.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "dkerov"
  system: workshop-system-dkerov
  consumesApis:
    - gateway-api-dkerov
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-dkerov
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "dkerov"
